[build]
  publish = "public"
  command = "hugo"

[[redirects]]
  from = "http://thesoderqvist.com/*"
  to = "https://thesoderqvist.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.thesoderqvist.com/*"
  to = "https://thesoderqvist.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.thesoderqvist.com/*"
  to = "https://thesoderqvist.com/:splat"
  status = 301
  force = true
